### PR TITLE
Various fixes to localsearch plugin

### PR DESCRIPTION
**Pull request by gwax**
* fixed <scrip> tag that should be a <script> tag
* localsearch now properly applies filters to assets and generated json
* localsearch caching should have fewer false negatives

### CODE REVIEW

**Comment by ralsina** [comment]
Awesome, thanks for the fixes!

**Comment by ralsina** [comment]
I had a branch pending that also touched this plugin, and I had forgotten to merge it. Can you check that all your fixes are still applied?

**Comment by gwax** [comment]
Looks all good to me.

**Comment by ralsina** [comment]
cool, thanks.

**Pull request merged**
