### PR TITLE
Add new rest_archiveorg plugin

### PR DESCRIPTION
**Pull request by SpotlightKid**
This plugin adds a reStructuredText directive to embed a player for video and
audio files from archive.org.

See the included README for more information.

### CODE REVIEW

**Comment by Aeyoun** [comment]
This plug-in’s name should contain “media” or “player”.

**Comment by SpotlightKid** [comment]
That would be a rather long name, e.g. `rest_archiveorg_player`. Most of the existing plugins like soundcloud, youtube or vimeo have short names, which do not confer much about their purpose either, not even that they are rest directives.

**Comment by Aeyoun** [comment]
This plugin kind of collides with [https://plugins.getnikola.com/#iarchiver](iarchiver) in terms of naming, so … yeah. Archive.org is most known for the Wayback Machine and not media hosting.

**Comment by SpotlightKid** [comment]
Do you have any suggestions for a better name?

**Comment by SpotlightKid** [comment]
I'm currently restructuring this plug-in. While this is ongoing, it isn't ready for merging. I'll report back when I have a version that I think is ready for merging again.

**Pull request closed without merging**
