### PR TITLE
Support http(s) URLs for postcast enclosure

### PR DESCRIPTION
**Pull request by anderbubble**
I decided to move my podcast episodes out of my nikola site source tree and into an object store. This change supports building a postcast from enclosures that are at an explicit full URL.

### CODE REVIEW

**Comment by anderbubble** [comment]
This change also adds a dependency on the requests library, to get the size of the file. Let me know if I need to do anything to document that dependency.

**Comment by anderbubble** [comment]
Fixed a linter error.

**Comment by anderbubble** [comment]
When I ported in upstream changes to my local install, explicit calls to category langs was breaking the plugin. I think my change at https://github.com/getnikola/plugins/pull/414/files#diff-7889d47a9a3d5d5c88ee3016dfe350e36cc274a366c77066f8057986a967540aL71-L72 fixes it, but I've never been 100% confident in my understanding of nikola i18n.

**Comment by anderbubble** [comment]
It looks like the remaining failing checks aren't in my code. Let me know if there's anything else I need to address.

**Comment by Kwpolska** [comment]
@anderbubble Can you merge/rebase `master` from the main repo into your branch?

**Comment by anderbubble** [comment]
@Kwpolska done. Let me know if you need anything else.

I've got another tiny change to PR separately, but I'll file that after this is merged.

**Comment by anderbubble** [comment]
@Kwpolska checking in to see if there's anything else you need to allow this to be merged.

**Review by Kwpolska — APPROVED** [review]

**Comment by anderbubble** [comment]
Thank you!

**Pull request merged**
