### PR TITLE
Adding plugin to import from Jekyll/Nikola sites

### PR DESCRIPTION
**Pull request by magmax**
Hi there!

I've created a plugin to import Jekyll/Octopress sites to Nikola.

I've taken almost all code from my previous project https://github.com/magmax/jekyll2nikola

### CODE REVIEW

**Comment by magmax** [comment]
Any news on this?

**Comment by Kwpolska** [comment]
Oh, sorry.  I completely forgot about it.  Thanks for the nudge.

Because I don’t have a Jekyll site handy, I’m merging now.  I trust you have tested it well enough.

**Comment by Kwpolska** [comment]
The plugin will appear on `plugins.getnikola.com` at midnight UTC.

**Comment by magmax** [comment]
It is not perfect, but I think it is a very good start point. Not all jekyll options are working in this version.

**Pull request merged**
