### PR TITLE
MAINT: Update tipue to 7.1 in localsearch

### PR DESCRIPTION
**Pull request by bashtage**
Update to the latest release

### CODE REVIEW

**Comment by bashtage** [comment]
Failure is due to a flake8 issue in another plugin.

**Comment by bashtage** [comment]
Fixed in #311

**Comment by bashtage** [comment]
Don't merge for now.  I need to diff the old againt 5.1 to see what had changed from stock tipue and port that in.

**Comment by bashtage** [comment]
All done. There weren't any to note.

**Comment by ralsina** [comment]
There you go, thx for the help!

**Pull request merged**
