### PR TITLE
Add plugin to send webmentions after deployment

### PR DESCRIPTION
**Pull request by bentasker**
This adds a plugin to detect external links in posts/pages and perform WebMention (the modern form of pingback) endpoint discovery on them in order to send a WebMention notification.

### CODE REVIEW

**Review by Kwpolska — APPROVED** [review]

**Comment by Kwpolska** [comment]
@bentasker Can you fix [the code style violations](https://github.com/getnikola/plugins/actions/runs/3665157434/jobs/6196259202)? (Running [`black`](https://github.com/psf/black) on your code should be enough to resolve those complaints.)

**Comment by bentasker** [comment]
Sure, done

**Comment by Kwpolska** [comment]
Thanks for your contribution!

**Comment by bentasker** [comment]
Thanks!

**Pull request merged**
